export const FETCH_BENEFITS_REQUEST = "FETCH_BENEFITS_REQUEST";
export const FETCH_BENEFITS_SUCCESS = "FETCH_BENEFITS_SUCCESS";
export const FETCH_BENEFITS_FAILURE = "FETCH_BENEFITS_FAILURE";
export const SELECT_BENEFITS_CHECKBOXES = "SELECT_BENEFITS_CHECKBOXES";
